# Generated by Django 5.1.1 on 2024-09-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream_entries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dream_entries.user",
            ),
        ),
    ]
