# Generated by Django 5.1.1 on 2024-11-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream_entries", "0002_alter_dream_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="user",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="dream_entries.user",
            ),
            preserve_default=False,
        ),
    ]
