# Generated by Django 5.1.1 on 2024-11-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dream_entries", "0004_alter_dream_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
